{
 "title": "Plant Monitor",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "content": "<div class=\"dashboard-header\">\n  <span>Plant Monitor v0.1</span> \n</div>\n"
  },
  {
   "title": "Air Humidity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "percent", "label": "Air Humidity" }
   ],
   "targets": [
    {
     "measurement": "IoT",
     "query": "SELECT \"Humidity\" FROM \"IoT\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "Humidity" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Air Temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 5, "y": 2 },
   "yaxes": [
    { "format": "short", "label": "Temperature" }
   ],
   "targets": [
    {
     "measurement": "IoT",
     "select": [
      [
       { "params": [ "Temperature" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Light intensity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 11, "y": 2 },
   "yaxes": [
    { "format": "none", "label": "Light intensity" }
   ],
   "targets": [
    {
     "measurement": "IoT",
     "query": "SELECT \"Ldr\" FROM \"IoT\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "Ldr" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Soil humidity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 2 },
   "yaxes": [
    { "format": "percent", "label": "Soil Humidity" }
   ],
   "targets": [
    {
     "measurement": "IoT",
     "query": "SELECT \"Soil\" FROM \"IoT\" ",
     "select": [
      [
       { "params": [ "Soil" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Hum",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 10 },
   "targets": [
    {
     "measurement": "IoT",
     "select": [
      [
       { "params": [ "Humidity" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Temp",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 5, "y": 10 },
   "targets": [
    {
     "measurement": "IoT",
     "select": [
      [
       { "params": [ "Temperature" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Light",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 11, "y": 10 },
   "targets": [
    {
     "measurement": "IoT",
     "select": [
      [
       { "params": [ "Ldr" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Soil",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 10 },
   "targets": [
    {
     "measurement": "IoT",
     "select": [
      [
       { "params": [ "Soil" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Hum",
   "type": "table",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 14 },
   "targets": [
    {
     "limit": "10",
     "measurement": "IoT",
     "select": [
      [
       { "params": [ "Humidity" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Temp",
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 5, "y": 14 },
   "targets": [
    {
     "limit": 10,
     "measurement": "IoT",
     "select": [
      [
       { "params": [ "Temperature" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Light",
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 11, "y": 14 },
   "targets": [
    {
     "limit": 10,
     "measurement": "IoT",
     "select": [
      [
       { "params": [ "Ldr" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Soil",
   "type": "table",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 14 },
   "targets": [
    {
     "limit": 10,
     "measurement": "IoT",
     "select": [
      [
       { "params": [ "Soil" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "DATA",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "measurement": "IoT",
     "query": "SELECT \"Soil\" FROM \"IoT\" ",
     "select": [
      [
       { "params": [ "Soil" ], "type": "field" }
      ],
      [
       { "params": [ "Humidity" ], "type": "field" }
      ],
      [
       { "params": [ "Temperature" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}