{
 "title": "Weather Monitor",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div class=\"dashboard-header\">\n  <span>Weather Monitor v0.1</span> \n</div>\n"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 2 },
   "options": {
    "content": "\n# Buenos Aires\n[Ciudad Autónoma de Buenos Aires](https://es.wikipedia.org/wiki/Buenos_Aires)\n\n\n\n"
   }
  },
  {
   "title": "Latitud - SMN",
   "type": "stat",
   "description": "Posición donde se toman las mediciones según el SMN ",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "LAT",
     "measurement": "measurement",
     "select": [
      [
       { "params": [ "smn_lat" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Longitud - SMN",
   "type": "stat",
   "description": "Posición donde se toman las mediciones según el SMN ",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "LON",
     "measurement": "measurement",
     "select": [
      [
       { "params": [ "smn_lon" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Presión Atmosférica (hPa) - SMN",
   "type": "stat",
   "description": "Presión atmosférica registrada por el SMN",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "hPa",
     "measurement": "measurement",
     "select": [
      [
       { "params": [ "smn_pressure" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Visibilidad - SMN",
   "type": "stat",
   "description": "Visibilidad registrada por el SMN",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "lengthkm" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "measurement",
     "select": [
      [
       { "params": [ "smn_visibility" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Temp - DHT22",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "DHT22",
     "measurement": "measurement",
     "select": [
      [
       { "params": [ "Temperature" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Hum - DHT22",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "DHT22",
     "measurement": "measurement",
     "select": [
      [
       { "params": [ "Humidity" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Light - Lumen",
   "type": "stat",
   "description": "El lux (símbolo: lx) es la unidad derivada del Sistema Internacional de Unidades para la iluminancia o nivel de iluminación. Equivale a un lumen /m². Se usa en la fotometría como medida de la iluminancia, tomando en cuenta las diferentes longitudes de onda según la función de luminosidad, un modelo estándar de la sensibilidad del ojo humano a la luz. ",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "Lumen",
     "measurement": "measurement",
     "select": [
      [
       { "params": [ "Lux" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Light - LDR",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "LDR",
     "measurement": "measurement",
     "select": [
      [
       { "params": [ "Ldr" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Soil",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "measurement",
     "select": [
      [
       { "params": [ "Soil" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Water",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "measurement",
     "select": [
      [
       { "params": [ "Water" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Air Temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "Temperature" }
   ],
   "targets": [
    {
     "alias": "DHT22",
     "measurement": "measurement",
     "select": [
      [
       { "params": [ "Temperature" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "SMN",
     "measurement": "measurement",
     "select": [
      [
       { "params": [ "smn_temp" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Air Humidity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 10 },
   "yaxes": [
    { "format": "percent", "label": "Air Humidity" }
   ],
   "targets": [
    {
     "alias": "DHT22",
     "measurement": "measurement",
     "query": "SELECT \"Humidity\" FROM \"IoT\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "Humidity" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "SMN",
     "measurement": "measurement",
     "query": "SELECT \"Humidity\" FROM \"IoT\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "smn_hum" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Light intensity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 10, "y": 10 },
   "yaxes": [
    { "format": "none", "label": "Light intensity" }
   ],
   "targets": [
    {
     "alias": "LDR",
     "measurement": "measurement",
     "query": "SELECT \"Ldr\" FROM \"IoT\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "Ldr" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "LUX",
     "measurement": "measurement",
     "query": "SELECT \"Ldr\" FROM \"IoT\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "Lux" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Soil humidity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "percent", "label": "Soil Humidity" }
   ],
   "targets": [
    {
     "alias": "Soil",
     "measurement": "measurement",
     "query": "SELECT \"Soil\" FROM \"IoT\" ",
     "select": [
      [
       { "params": [ "Soil" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Water ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 10 },
   "yaxes": [
    { "format": "none", "label": "Whather" }
   ],
   "targets": [
    {
     "alias": "Water",
     "measurement": "measurement",
     "query": "SELECT \"Soil\" FROM \"IoT\" ",
     "select": [
      [
       { "params": [ "Water" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Últimos registros:  Temp",
   "type": "table-old",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 18 },
   "targets": [
    {
     "limit": "10",
     "measurement": "measurement",
     "select": [
      [
       { "params": [ "Temperature" ], "type": "field" }
      ]
     ]
    },
    {
     "limit": "10",
     "measurement": "measurement",
     "select": [
      [
       { "params": [ "smn_temp" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Últimos registros: Hum",
   "type": "table-old",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 18 },
   "targets": [
    {
     "limit": "10",
     "measurement": "measurement",
     "select": [
      [
       { "params": [ "Humidity" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Últimos registros: Light",
   "type": "table-old",
   "gridPos": { "h": 5, "w": 7, "x": 12, "y": 18 },
   "targets": [
    {
     "limit": 10,
     "measurement": "measurement",
     "select": [
      [
       { "params": [ "Ldr" ], "type": "field" }
      ]
     ]
    },
    {
     "limit": 10,
     "measurement": "measurement",
     "select": [
      [
       { "params": [ "Lux" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Últimos registros: Soil",
   "type": "table-old",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 18 },
   "targets": [
    {
     "limit": 10,
     "measurement": "measurement",
     "select": [
      [
       { "params": [ "Soil" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "DATA",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "measurement",
     "query": "SELECT \"Soil\" FROM \"IoT\" ",
     "select": [
      [
       { "params": [ "Humidity" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "measurement",
     "query": "SELECT \"Soil\" FROM \"IoT\" ",
     "select": [
      [
       { "params": [ "Temperature" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "measurement",
     "query": "SELECT \"Soil\" FROM \"IoT\" ",
     "select": [
      [
       { "params": [ "Ldr" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "measurement",
     "query": "SELECT \"Soil\" FROM \"IoT\" ",
     "select": [
      [
       { "params": [ "Lux" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}